### ISSUE TITLE
Accessing databricks from behind a proxy

### ISSUE THREAD

**Issue by daragallagher** [edmunds/databricks-rest-client#21]
Many enterprises use web proxies.  

But unfortunately it seems to me that it is not possible to use the databricks-rest-client library in such an environment because of the use of Apache HttpClient.  This class has a long known issue whereby the standard Java system properties relating to proxy setup (http.proxyHost, http.proxyPort, https.proxyHost, https.proxyPort and http.nonProxyHosts) are ignored by default. 

The suggested solution is to call useSystemProperties() on the HttpClientBuilder used to create the client.

This (I think!) would require a small change to the first line of DatabricksRestClientImpl.initClient(...) 
```
//    HttpClientBuilder clientBuilder = HttpClients.custom()
    HttpClientBuilder clientBuilder = HttpClientBuilder.create().useSystemProperties() // pick up Java proxy settings
```
However I'm a little uncomfortable submitting a pull request for this change as I'm not sure if useSystemProperties() will stomp some other aspects of the build configuration which is important for communicating with a databricks endpoint.  Or maybe there is a work around for this issue that I haven't spotted.

(Btw. I'm using this library through the databricks-maven-plugin - and our build/CI system is secured behind a proxy which I think is a fairly common set-up.)

**Comment by samshuster** [comment]
hey @daragallagher thanks for reporting this!

Can you confirm that the above solution works for you? Otherwise I will have a difficult time testing that it would fix your issue.

Not sure if you saw, but there is a suite of integration tests that you can run via this command:
```
## Integration Tests
IMPORTANT: integration tests do not execute automatically as part of a build.
It is your responsibility (and Pull Request Reviewers) to make sure the integration tests
pass before merging in code.

### Setup
You need to set the following environment properties in your .bash_profile
```bash
export DB_USER=myuser@domain.com
export DB_PASSWORD=mypassword
export DB_URL=my-databricks-account.databricks.com
export DB_TOKEN=my-token
```
```
In order for the integration tests to run, you must
have a valid token for the user in question.
Here is how to set it up: [Set up Tokens](https://docs.databricks.com/api/latest/authentication.html)

### Executing Integration Tests
mvn clean install org.apache.maven.plugins:maven-failsafe-plugin:integration-test
```

If that suite of integration tests works then we can feel pretty confident that things will work as expected. I will go ahead and add your change and make sure they pass now.

**Comment by daragallagher** [comment]
Hi Sam.  I was about to run the tests myself :) - but I see you've implemented the change already so I've pulled your changes and will test that the proxy settings are being respected against the issue-21/proxy-fix branch in our "production" environment.  Cheers! Dara.

**Comment by daragallagher** [comment]
It looks good Sam!  Cheers! Dara.

**Comment by daragallagher** [comment]
Looks good Sam.  Cheers! Dara.
(Btw. sorry I accidentally click the close issue button on submit - so I've re-opened it - not sure about your issue workflow.)

**Comment by samshuster** [comment]
woohoo great, we will get this merged and released sometime today!
