### ISSUE TITLE
hi, is this project still maintained?

### ISSUE THREAD

**Issue by cornelcreanga** [edmunds/databricks-rest-client#58]

**Comment by samshuster** [comment]
hi cornel, apologies for the late response, although dev work has largely died down (the project currently meets all of our org's needs), we will still are willing work on it.

Unfortunately, we seem to have not had the correct settings setup to get notified about new issues and PRs though which is why it has appeared dead since August.

Thanks for reaching out to me on LinkedIn! (the reason why I came to look here)

**Comment by cornelcreanga** [comment]
tkx
